[tool.poetry]
name = "til"
version = "0.1.0"
description = ""
authors = ["hyeseong-dev <hyeseong43@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.8"
jupyterlab = "^4.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
